# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raut/Downloads/yantrium-qt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raut/Downloads/yantrium-qt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raut/Downloads/yantrium-qt/CMakeFiles /home/raut/Downloads/yantrium-qt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raut/Downloads/yantrium-qt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Yantrium

# Build rule for target.
Yantrium: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Yantrium
.PHONY : Yantrium

# fast build rule for target.
Yantrium/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/build
.PHONY : Yantrium/fast

#=============================================================================
# Target rules for targets named Yantrium_autogen_timestamp_deps

# Build rule for target.
Yantrium_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Yantrium_autogen_timestamp_deps
.PHONY : Yantrium_autogen_timestamp_deps

# fast build rule for target.
Yantrium_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium_autogen_timestamp_deps.dir/build.make CMakeFiles/Yantrium_autogen_timestamp_deps.dir/build
.PHONY : Yantrium_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Yantrium_autogen

# Build rule for target.
Yantrium_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Yantrium_autogen
.PHONY : Yantrium_autogen

# fast build rule for target.
Yantrium_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium_autogen.dir/build.make CMakeFiles/Yantrium_autogen.dir/build
.PHONY : Yantrium_autogen/fast

Yantrium_autogen/3YJK5W5UP7/qrc_qml.o: Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.o
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.o

# target to build an object file
Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.o
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.o

Yantrium_autogen/3YJK5W5UP7/qrc_qml.i: Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.i
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.i

# target to preprocess a source file
Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.i
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.i

Yantrium_autogen/3YJK5W5UP7/qrc_qml.s: Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.s
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.s

# target to generate assembly for a file
Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.s
.PHONY : Yantrium_autogen/3YJK5W5UP7/qrc_qml.cpp.s

Yantrium_autogen/mocs_compilation.o: Yantrium_autogen/mocs_compilation.cpp.o
.PHONY : Yantrium_autogen/mocs_compilation.o

# target to build an object file
Yantrium_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/mocs_compilation.cpp.o
.PHONY : Yantrium_autogen/mocs_compilation.cpp.o

Yantrium_autogen/mocs_compilation.i: Yantrium_autogen/mocs_compilation.cpp.i
.PHONY : Yantrium_autogen/mocs_compilation.i

# target to preprocess a source file
Yantrium_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/mocs_compilation.cpp.i
.PHONY : Yantrium_autogen/mocs_compilation.cpp.i

Yantrium_autogen/mocs_compilation.s: Yantrium_autogen/mocs_compilation.cpp.s
.PHONY : Yantrium_autogen/mocs_compilation.s

# target to generate assembly for a file
Yantrium_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/Yantrium_autogen/mocs_compilation.cpp.s
.PHONY : Yantrium_autogen/mocs_compilation.cpp.s

src/app_controller.o: src/app_controller.cpp.o
.PHONY : src/app_controller.o

# target to build an object file
src/app_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/app_controller.cpp.o
.PHONY : src/app_controller.cpp.o

src/app_controller.i: src/app_controller.cpp.i
.PHONY : src/app_controller.i

# target to preprocess a source file
src/app_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/app_controller.cpp.i
.PHONY : src/app_controller.cpp.i

src/app_controller.s: src/app_controller.cpp.s
.PHONY : src/app_controller.s

# target to generate assembly for a file
src/app_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/app_controller.cpp.s
.PHONY : src/app_controller.cpp.s

src/core/database/addon_dao.o: src/core/database/addon_dao.cpp.o
.PHONY : src/core/database/addon_dao.o

# target to build an object file
src/core/database/addon_dao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/addon_dao.cpp.o
.PHONY : src/core/database/addon_dao.cpp.o

src/core/database/addon_dao.i: src/core/database/addon_dao.cpp.i
.PHONY : src/core/database/addon_dao.i

# target to preprocess a source file
src/core/database/addon_dao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/addon_dao.cpp.i
.PHONY : src/core/database/addon_dao.cpp.i

src/core/database/addon_dao.s: src/core/database/addon_dao.cpp.s
.PHONY : src/core/database/addon_dao.s

# target to generate assembly for a file
src/core/database/addon_dao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/addon_dao.cpp.s
.PHONY : src/core/database/addon_dao.cpp.s

src/core/database/database_manager.o: src/core/database/database_manager.cpp.o
.PHONY : src/core/database/database_manager.o

# target to build an object file
src/core/database/database_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/database_manager.cpp.o
.PHONY : src/core/database/database_manager.cpp.o

src/core/database/database_manager.i: src/core/database/database_manager.cpp.i
.PHONY : src/core/database/database_manager.i

# target to preprocess a source file
src/core/database/database_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/database_manager.cpp.i
.PHONY : src/core/database/database_manager.cpp.i

src/core/database/database_manager.s: src/core/database/database_manager.cpp.s
.PHONY : src/core/database/database_manager.s

# target to generate assembly for a file
src/core/database/database_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/database/database_manager.cpp.s
.PHONY : src/core/database/database_manager.cpp.s

src/core/models/tmdb_models.o: src/core/models/tmdb_models.cpp.o
.PHONY : src/core/models/tmdb_models.o

# target to build an object file
src/core/models/tmdb_models.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/models/tmdb_models.cpp.o
.PHONY : src/core/models/tmdb_models.cpp.o

src/core/models/tmdb_models.i: src/core/models/tmdb_models.cpp.i
.PHONY : src/core/models/tmdb_models.i

# target to preprocess a source file
src/core/models/tmdb_models.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/models/tmdb_models.cpp.i
.PHONY : src/core/models/tmdb_models.cpp.i

src/core/models/tmdb_models.s: src/core/models/tmdb_models.cpp.s
.PHONY : src/core/models/tmdb_models.s

# target to generate assembly for a file
src/core/models/tmdb_models.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/models/tmdb_models.cpp.s
.PHONY : src/core/models/tmdb_models.cpp.s

src/core/services/configuration.o: src/core/services/configuration.cpp.o
.PHONY : src/core/services/configuration.o

# target to build an object file
src/core/services/configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/configuration.cpp.o
.PHONY : src/core/services/configuration.cpp.o

src/core/services/configuration.i: src/core/services/configuration.cpp.i
.PHONY : src/core/services/configuration.i

# target to preprocess a source file
src/core/services/configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/configuration.cpp.i
.PHONY : src/core/services/configuration.cpp.i

src/core/services/configuration.s: src/core/services/configuration.cpp.s
.PHONY : src/core/services/configuration.s

# target to generate assembly for a file
src/core/services/configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/configuration.cpp.s
.PHONY : src/core/services/configuration.cpp.s

src/core/services/id_parser.o: src/core/services/id_parser.cpp.o
.PHONY : src/core/services/id_parser.o

# target to build an object file
src/core/services/id_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/id_parser.cpp.o
.PHONY : src/core/services/id_parser.cpp.o

src/core/services/id_parser.i: src/core/services/id_parser.cpp.i
.PHONY : src/core/services/id_parser.i

# target to preprocess a source file
src/core/services/id_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/id_parser.cpp.i
.PHONY : src/core/services/id_parser.cpp.i

src/core/services/id_parser.s: src/core/services/id_parser.cpp.s
.PHONY : src/core/services/id_parser.s

# target to generate assembly for a file
src/core/services/id_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/id_parser.cpp.s
.PHONY : src/core/services/id_parser.cpp.s

src/core/services/tmdb_data_extractor.o: src/core/services/tmdb_data_extractor.cpp.o
.PHONY : src/core/services/tmdb_data_extractor.o

# target to build an object file
src/core/services/tmdb_data_extractor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_data_extractor.cpp.o
.PHONY : src/core/services/tmdb_data_extractor.cpp.o

src/core/services/tmdb_data_extractor.i: src/core/services/tmdb_data_extractor.cpp.i
.PHONY : src/core/services/tmdb_data_extractor.i

# target to preprocess a source file
src/core/services/tmdb_data_extractor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_data_extractor.cpp.i
.PHONY : src/core/services/tmdb_data_extractor.cpp.i

src/core/services/tmdb_data_extractor.s: src/core/services/tmdb_data_extractor.cpp.s
.PHONY : src/core/services/tmdb_data_extractor.s

# target to generate assembly for a file
src/core/services/tmdb_data_extractor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_data_extractor.cpp.s
.PHONY : src/core/services/tmdb_data_extractor.cpp.s

src/core/services/tmdb_search_service.o: src/core/services/tmdb_search_service.cpp.o
.PHONY : src/core/services/tmdb_search_service.o

# target to build an object file
src/core/services/tmdb_search_service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_search_service.cpp.o
.PHONY : src/core/services/tmdb_search_service.cpp.o

src/core/services/tmdb_search_service.i: src/core/services/tmdb_search_service.cpp.i
.PHONY : src/core/services/tmdb_search_service.i

# target to preprocess a source file
src/core/services/tmdb_search_service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_search_service.cpp.i
.PHONY : src/core/services/tmdb_search_service.cpp.i

src/core/services/tmdb_search_service.s: src/core/services/tmdb_search_service.cpp.s
.PHONY : src/core/services/tmdb_search_service.s

# target to generate assembly for a file
src/core/services/tmdb_search_service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_search_service.cpp.s
.PHONY : src/core/services/tmdb_search_service.cpp.s

src/core/services/tmdb_service.o: src/core/services/tmdb_service.cpp.o
.PHONY : src/core/services/tmdb_service.o

# target to build an object file
src/core/services/tmdb_service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_service.cpp.o
.PHONY : src/core/services/tmdb_service.cpp.o

src/core/services/tmdb_service.i: src/core/services/tmdb_service.cpp.i
.PHONY : src/core/services/tmdb_service.i

# target to preprocess a source file
src/core/services/tmdb_service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_service.cpp.i
.PHONY : src/core/services/tmdb_service.cpp.i

src/core/services/tmdb_service.s: src/core/services/tmdb_service.cpp.s
.PHONY : src/core/services/tmdb_service.s

# target to generate assembly for a file
src/core/services/tmdb_service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/core/services/tmdb_service.cpp.s
.PHONY : src/core/services/tmdb_service.cpp.s

src/features/addons/logic/addon_client.o: src/features/addons/logic/addon_client.cpp.o
.PHONY : src/features/addons/logic/addon_client.o

# target to build an object file
src/features/addons/logic/addon_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_client.cpp.o
.PHONY : src/features/addons/logic/addon_client.cpp.o

src/features/addons/logic/addon_client.i: src/features/addons/logic/addon_client.cpp.i
.PHONY : src/features/addons/logic/addon_client.i

# target to preprocess a source file
src/features/addons/logic/addon_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_client.cpp.i
.PHONY : src/features/addons/logic/addon_client.cpp.i

src/features/addons/logic/addon_client.s: src/features/addons/logic/addon_client.cpp.s
.PHONY : src/features/addons/logic/addon_client.s

# target to generate assembly for a file
src/features/addons/logic/addon_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_client.cpp.s
.PHONY : src/features/addons/logic/addon_client.cpp.s

src/features/addons/logic/addon_installer.o: src/features/addons/logic/addon_installer.cpp.o
.PHONY : src/features/addons/logic/addon_installer.o

# target to build an object file
src/features/addons/logic/addon_installer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_installer.cpp.o
.PHONY : src/features/addons/logic/addon_installer.cpp.o

src/features/addons/logic/addon_installer.i: src/features/addons/logic/addon_installer.cpp.i
.PHONY : src/features/addons/logic/addon_installer.i

# target to preprocess a source file
src/features/addons/logic/addon_installer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_installer.cpp.i
.PHONY : src/features/addons/logic/addon_installer.cpp.i

src/features/addons/logic/addon_installer.s: src/features/addons/logic/addon_installer.cpp.s
.PHONY : src/features/addons/logic/addon_installer.s

# target to generate assembly for a file
src/features/addons/logic/addon_installer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_installer.cpp.s
.PHONY : src/features/addons/logic/addon_installer.cpp.s

src/features/addons/logic/addon_repository.o: src/features/addons/logic/addon_repository.cpp.o
.PHONY : src/features/addons/logic/addon_repository.o

# target to build an object file
src/features/addons/logic/addon_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_repository.cpp.o
.PHONY : src/features/addons/logic/addon_repository.cpp.o

src/features/addons/logic/addon_repository.i: src/features/addons/logic/addon_repository.cpp.i
.PHONY : src/features/addons/logic/addon_repository.i

# target to preprocess a source file
src/features/addons/logic/addon_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_repository.cpp.i
.PHONY : src/features/addons/logic/addon_repository.cpp.i

src/features/addons/logic/addon_repository.s: src/features/addons/logic/addon_repository.cpp.s
.PHONY : src/features/addons/logic/addon_repository.s

# target to generate assembly for a file
src/features/addons/logic/addon_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/logic/addon_repository.cpp.s
.PHONY : src/features/addons/logic/addon_repository.cpp.s

src/features/addons/models/addon_config.o: src/features/addons/models/addon_config.cpp.o
.PHONY : src/features/addons/models/addon_config.o

# target to build an object file
src/features/addons/models/addon_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_config.cpp.o
.PHONY : src/features/addons/models/addon_config.cpp.o

src/features/addons/models/addon_config.i: src/features/addons/models/addon_config.cpp.i
.PHONY : src/features/addons/models/addon_config.i

# target to preprocess a source file
src/features/addons/models/addon_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_config.cpp.i
.PHONY : src/features/addons/models/addon_config.cpp.i

src/features/addons/models/addon_config.s: src/features/addons/models/addon_config.cpp.s
.PHONY : src/features/addons/models/addon_config.s

# target to generate assembly for a file
src/features/addons/models/addon_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_config.cpp.s
.PHONY : src/features/addons/models/addon_config.cpp.s

src/features/addons/models/addon_manifest.o: src/features/addons/models/addon_manifest.cpp.o
.PHONY : src/features/addons/models/addon_manifest.o

# target to build an object file
src/features/addons/models/addon_manifest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_manifest.cpp.o
.PHONY : src/features/addons/models/addon_manifest.cpp.o

src/features/addons/models/addon_manifest.i: src/features/addons/models/addon_manifest.cpp.i
.PHONY : src/features/addons/models/addon_manifest.i

# target to preprocess a source file
src/features/addons/models/addon_manifest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_manifest.cpp.i
.PHONY : src/features/addons/models/addon_manifest.cpp.i

src/features/addons/models/addon_manifest.s: src/features/addons/models/addon_manifest.cpp.s
.PHONY : src/features/addons/models/addon_manifest.s

# target to generate assembly for a file
src/features/addons/models/addon_manifest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/addon_manifest.cpp.s
.PHONY : src/features/addons/models/addon_manifest.cpp.s

src/features/addons/models/catalog_definition.o: src/features/addons/models/catalog_definition.cpp.o
.PHONY : src/features/addons/models/catalog_definition.o

# target to build an object file
src/features/addons/models/catalog_definition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/catalog_definition.cpp.o
.PHONY : src/features/addons/models/catalog_definition.cpp.o

src/features/addons/models/catalog_definition.i: src/features/addons/models/catalog_definition.cpp.i
.PHONY : src/features/addons/models/catalog_definition.i

# target to preprocess a source file
src/features/addons/models/catalog_definition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/catalog_definition.cpp.i
.PHONY : src/features/addons/models/catalog_definition.cpp.i

src/features/addons/models/catalog_definition.s: src/features/addons/models/catalog_definition.cpp.s
.PHONY : src/features/addons/models/catalog_definition.s

# target to generate assembly for a file
src/features/addons/models/catalog_definition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/features/addons/models/catalog_definition.cpp.s
.PHONY : src/features/addons/models/catalog_definition.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player/mdk_player.o: src/player/mdk_player.cpp.o
.PHONY : src/player/mdk_player.o

# target to build an object file
src/player/mdk_player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/mdk_player.cpp.o
.PHONY : src/player/mdk_player.cpp.o

src/player/mdk_player.i: src/player/mdk_player.cpp.i
.PHONY : src/player/mdk_player.i

# target to preprocess a source file
src/player/mdk_player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/mdk_player.cpp.i
.PHONY : src/player/mdk_player.cpp.i

src/player/mdk_player.s: src/player/mdk_player.cpp.s
.PHONY : src/player/mdk_player.s

# target to generate assembly for a file
src/player/mdk_player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/mdk_player.cpp.s
.PHONY : src/player/mdk_player.cpp.s

src/player/player_bridge.o: src/player/player_bridge.cpp.o
.PHONY : src/player/player_bridge.o

# target to build an object file
src/player/player_bridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/player_bridge.cpp.o
.PHONY : src/player/player_bridge.cpp.o

src/player/player_bridge.i: src/player/player_bridge.cpp.i
.PHONY : src/player/player_bridge.i

# target to preprocess a source file
src/player/player_bridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/player_bridge.cpp.i
.PHONY : src/player/player_bridge.cpp.i

src/player/player_bridge.s: src/player/player_bridge.cpp.s
.PHONY : src/player/player_bridge.s

# target to generate assembly for a file
src/player/player_bridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Yantrium.dir/build.make CMakeFiles/Yantrium.dir/src/player/player_bridge.cpp.s
.PHONY : src/player/player_bridge.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Yantrium_autogen"
	@echo "... Yantrium_autogen_timestamp_deps"
	@echo "... Yantrium"
	@echo "... Yantrium_autogen/3YJK5W5UP7/qrc_qml.o"
	@echo "... Yantrium_autogen/3YJK5W5UP7/qrc_qml.i"
	@echo "... Yantrium_autogen/3YJK5W5UP7/qrc_qml.s"
	@echo "... Yantrium_autogen/mocs_compilation.o"
	@echo "... Yantrium_autogen/mocs_compilation.i"
	@echo "... Yantrium_autogen/mocs_compilation.s"
	@echo "... src/app_controller.o"
	@echo "... src/app_controller.i"
	@echo "... src/app_controller.s"
	@echo "... src/core/database/addon_dao.o"
	@echo "... src/core/database/addon_dao.i"
	@echo "... src/core/database/addon_dao.s"
	@echo "... src/core/database/database_manager.o"
	@echo "... src/core/database/database_manager.i"
	@echo "... src/core/database/database_manager.s"
	@echo "... src/core/models/tmdb_models.o"
	@echo "... src/core/models/tmdb_models.i"
	@echo "... src/core/models/tmdb_models.s"
	@echo "... src/core/services/configuration.o"
	@echo "... src/core/services/configuration.i"
	@echo "... src/core/services/configuration.s"
	@echo "... src/core/services/id_parser.o"
	@echo "... src/core/services/id_parser.i"
	@echo "... src/core/services/id_parser.s"
	@echo "... src/core/services/tmdb_data_extractor.o"
	@echo "... src/core/services/tmdb_data_extractor.i"
	@echo "... src/core/services/tmdb_data_extractor.s"
	@echo "... src/core/services/tmdb_search_service.o"
	@echo "... src/core/services/tmdb_search_service.i"
	@echo "... src/core/services/tmdb_search_service.s"
	@echo "... src/core/services/tmdb_service.o"
	@echo "... src/core/services/tmdb_service.i"
	@echo "... src/core/services/tmdb_service.s"
	@echo "... src/features/addons/logic/addon_client.o"
	@echo "... src/features/addons/logic/addon_client.i"
	@echo "... src/features/addons/logic/addon_client.s"
	@echo "... src/features/addons/logic/addon_installer.o"
	@echo "... src/features/addons/logic/addon_installer.i"
	@echo "... src/features/addons/logic/addon_installer.s"
	@echo "... src/features/addons/logic/addon_repository.o"
	@echo "... src/features/addons/logic/addon_repository.i"
	@echo "... src/features/addons/logic/addon_repository.s"
	@echo "... src/features/addons/models/addon_config.o"
	@echo "... src/features/addons/models/addon_config.i"
	@echo "... src/features/addons/models/addon_config.s"
	@echo "... src/features/addons/models/addon_manifest.o"
	@echo "... src/features/addons/models/addon_manifest.i"
	@echo "... src/features/addons/models/addon_manifest.s"
	@echo "... src/features/addons/models/catalog_definition.o"
	@echo "... src/features/addons/models/catalog_definition.i"
	@echo "... src/features/addons/models/catalog_definition.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player/mdk_player.o"
	@echo "... src/player/mdk_player.i"
	@echo "... src/player/mdk_player.s"
	@echo "... src/player/player_bridge.o"
	@echo "... src/player/player_bridge.i"
	@echo "... src/player/player_bridge.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

